config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles

  # get '/:id/profile', to: 'profiles#show', as: 'user_profile'
  resource :profile, only: [:show, :edit, :create, :update, :destroy]

  resources :accounts, only: [:show]

  root to: 'articles#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :content, presence: true
  # validates :content, length: { minimum: 2, maximum: 50 }

  belongs_to :user

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :account_name, presence: true
  validates :account_name, uniqueness: true

  validates :email, presence: true
  validates :password, presence: true

  has_many :articles, dependent: :destroy

  has_one :profile, dependent: :destroy
  has_one_attached :avatar



end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to profile_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # deviseに追加したaccount_nameを受け取れるようにする
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account_name])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path,
                  notice: 'articleを作成しました'
    else
      flash.now[:error] = '作成に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy!
    # redirect_to articles_path, status: :see_other, notice: '削除に成功しました'
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def show
      @profile = current_user.profile
      @user = current_user
    end

  # def new
  #   @profile = current_user.build_profile
  # end

  # def create
  #   @profile = current_user.build_profile(profile_params)
  #   if @profile.save
  #     redirect_to root_path,
  #     notice: 'アバターを登録しました'
  #   else
  #     render :new
  #   end
  # end

  def edit
    @profile = current_user.profile
  end

  def update
    @profile = current_user.profile
    @profile.assign_attributes(profile_params)
    redirect_to profile_path
  end

  private
  def profile_params
    params.require(:profile).permit(:avatar)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @user.build_profile
  end

# def create
#   @user = User.new
#   if @user.save
#     Profile.create
#     sign_in(@user)
#     redirect_to profile_path(@user)
# end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/show.html.haml
.container
  = link_to '←', root_path
  %br/
  .profile-top
    %p.account-name= @user.account_name

    %div
      - if @user.avatar&.attached?
        = image_tag @user.profile.avatar_image, class: 'avatar-img'
      - else
        = image_tag "default-avatar.png", class: "avatar-img"
    %br/

  - @user.articles.each do |article|
    = article.content
    %br/

app/views/articles/index.html.haml
.container
  - @articles.each do |article|
    .article-account-name
      = link_to article.user.account_name, account_path(article.user_id)
    .article-content
      = article.content
  = link_to 'Sign out', destroy_user_session_path, turbo_method: :delete, class: 'btn-secondary'

app/views/articles/show.html.erb
<div class="container">
  <div class='profile-top'>

    <%# アカウント名を入れる %>
    <p class="account-name"><%= @user.account_name %></p>

      <%= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f| %>
          <div>
            <%# defaultのアバター %>
            <%= image_tag "default-avatar.png", class: "avatar-img" %>

            <%# プロフィールのアバターを変更する %>
            <%#= f.file_field :avatar %>
            <%#= f.submit 'change', class: 'btn-primary' %>

          </div>
      <% end %>
  </div>

  <% user.articles.each do |article| %>
    <%= article.content %>
  <% end %>

</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || "Final Blog App"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/manifest.json", :rel => "manifest"}/
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
  %body
    = yield

app/views/profiles/show.html.haml
.container
  = link_to '←', root_path
  %br/
  .profile-top
    %p.account-name= @user.account_name
    = form_with(model: @profile, url: profile_path(@user), method: 'put', local: true) do |f|
      %div
        - f.label :avatar, 'アバター'
        - if @user.avatar&.attached?
          = image_tag @user.profile.avatar_image, class: 'avatar-img'
        - else
          = image_tag "default-avatar.png", class: "avatar-img"
        = f.file_field :avatar
        %br/
        = f.submit 'change', class: 'btn-primary'
  - @user.articles.each do |article|
    = article.content
    %br/